---
- name: Import Nodesource RPM key.
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items: "{{ nodejs_rpm_key }}"

- name: Add Nodesource repositories for Node.js.
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ nodejs_repositories }}"

- name: Ensure Node.js AppStream module is disabled (CentOS 8+).
  command: yum module disable -y nodejs
  args:
    warn: false
  register: module_disable
  changed_when: "'Nothing to do.' not in module_disable.stdout"
  when: ansible_distribution_major_version|int >= 8

- name: Ensure Node.js and npm are installed.
  yum:
    name: "nodejs-{{ nodejs_version|regex_replace('x', '') }}*"
    state: present
    enablerepo: nodesource
